version: '2'
services:
  web:
    image: nginx
    volumes:
      - './dist:/usr/share/nginx/html'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
      - './.htpasswd:/etc/nginx/.htpasswd'
    restart: unless-stopped
    ports:
      - "80:80"
