version: '2'
services:
 web:
  image: nginx
  volumes:
    - '.dist:/usr/share/nginx/html'
  restart: unless-stopped
  #ports:
   #- "8080:80"
  environment:
   - NGINX_HOST=frontend.midominio.com
   - NGINX_PORT=80
   - VIRTUAL_HOST=frontend.midominio.com
   - LETSENCRYPT_HOST=frontend.midominio.com
   - LETSENCRYPT_EMAIL=info@midominio.com

networks:
  default:
    external:
      name: proxy
