version: '2'
services:
 app:
  build: .
  restart: unless-stopped
  environment:
   - VIRTUAL_HOST=api.midominio.com
   - LETSENCRYPT_HOST=api.midominio.com
   - LETSENCRYPT_EMAIL=info@midominio.com

networks:
  default:
    external:
      name: proxy
